### ISSUE TITLE
Explore a uarray and MoA integration example

### ISSUE THREAD

**Issue by dcharbon** [Quansight-Labs/uarray#130]
Discuss an approach to using MoA in uarray, set the stage for #122

**Comment by saulshanabrook** [comment]
We (@hameerabbasi, @costrouc, @mpeaton) had a meeting last week to discuss this. We went into some detail of the MoA API that Chris has been working on.

The general approach we outlined is:

1. User uses `uarray` to build up some array calls with `metadsl`
2. The metadsl graph is built
3. Then we translate this to a graph of MoA calls instead of uarray calls
4. Then we use MoA to compile these calls
