### ISSUE TITLE
add a determine_backend context manager?

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/uarray#198]
So, I think we need something like

```
with unumpy.determine_backend(x):
    do_stuff
```
Where `determine_backend` checks if `x` is supported by any of the registered backends. And those backends need to auto-register on import.

Does this seem like a good idea? Or are these better ones to make library code that supports some generic array type work without the user having to set a backend?

For reference: https://mail.python.org/pipermail/numpy-discussion/2019-September/079991.html discusses the need of having library code work without the user setting a backend explicitly.

**Comment by hameerabbasi** [comment]
The reason I didn't do this is so backends can be kept separate from array objects. Right now, `__ua_convert__` might not exist, and that backend would then take precedence over all others. If we make it compulsory, which would solve other issues as well, then we would have to change SciPy.

One possible resolution to this is to drop `ua.Dispatchable` completely, and make an object have a `__ua_backend__` field... But that'd again, couple objects to backends, and provide disadvantages if it doesn't exist.

**Comment by rgommers** [comment]
I don't think I understand your replies @hameerabbasi, except "some pros, some cons".

> One can always register a backend, and then there's no need to use it explicitly, it'll just work based on the array types.

If "one" is the library not the end user, is there a reason not to do this? E.g., on `import dask.array` register `dask_backend`? A user can't really get a hold of a dask array without that import, so should be reliable I'd think.

**Comment by hameerabbasi** [comment]
Besides overhead, I can think of only that it clutters global state unnecessarily. But I'll also assume that a library dev won't unnecessarily import anything so I'd say it should be fine.

**Comment by peterbell10** [comment]
> is there a reason not to do this? E.g., on `import dask.array` register `dask_backend`?

This assumes that the user wants to use the backend given by `dask`; the user might want e.g. @hameerabbasi's example of a `dask` backend that automatically sets the chunk size. Such a backend would now be in competition with the default registered backend.

**Comment by rgommers** [comment]
> > is there a reason not to do this? E.g., on `import dask.array` register `dask_backend`?
> 
> This assumes that the user wants to use the backend given by `dask`; the user might want e.g. @hameerabbasi's example of a `dask` backend that automatically sets the chunk size. Such a backend would now be in competition with the default registered backend.

Could that be avoided by only auto-registering when there's no other backend for an array type already present and trying backends in most recently registered order first?


I realize that there may be quite a few tricky things in my proposal. Happy to hear about better solutions of course. I just feel like the current design lacks a strong answer for what library authors should do here. Relying on the user to register every backend assumes a level of understanding of what happens when they call `numpy_func(dask_array_input)` that's too high.

**Comment by dhirschfeld** [comment]
> *This assumes that the user wants to use the backend given by dask;*

Speaking as a (potential) user, registering a backend as available would be fine but I wouldn't want it to be automatically used.

If there's a priority order how would it know where to go in the hierarchy? As a user I'd like control over what backends will be considered for use and in what order they should be considered (by default). I'd also like the ability to specify a particular backend to use on an operation-by-operation basis (operation ≈ block of code). i.e. to override the default priority order

If we're going to go for full-flexibility rather than specifying the exact backend to use for a paticular block of code it might be useful to allow specifying a different priority order (different set of backends to use) for that block

**Comment by peterbell10** [comment]
> Could that be avoided by only auto-registering when there's no other backend for an array type already present and trying backends in most recently registered order first?

This would help but there's still the possibility of falling back to the auto-registered backend when the user-specificed backend returns `NotImplemented`. That could be somewhat unexpected and potentially hard to debug.

An alternative proposal: how about adding a backend that checks for something like `__ua_backend__` in the dispatchable values, else falling back to `numpy`? This could be installed as the default global backend so that like `__array_function__` it "just does the right thing" most of the time. Power-users would then be able to replace this global backend to remove the behaviour and of course `set_backend` calls would always have a higher priority anyway.

**Comment by hameerabbasi** [comment]
And setting that as the global backend? Seems feasible.

**Comment by rgommers** [comment]
I like that idea. Seems less invasive than what I proposed, and it should indeed "just do the right thing".

**Comment by hameerabbasi** [comment]
So, I finally figured out a design for this. I'll put the signature here:

```
def determine_backend(obj, mark, domain):
    """
    Returns a backend that can accept `obj` without any coercion.

    Parameters
    ----------
    obj : object
        The object to determine a suitable backend for.
    mark: object
        The mark to check the object against.
    domain: str
        The domain of the backend.

    Returns
    -------
    The backend object.
    """"
```

Then NumPy can wrap this as, say,

```
def determine_backend(x):
    return ua.determine_backend(x, np.ndarray, "numpy")
```

**Comment by hameerabbasi** [comment]
I just ran into needing this for `udiff` when removing `skip_backend` as well.
